Repository trunk-rs/trunk, pull requests merged in 2023-03, with the labels that each got.

#505 tailwindcss support
  CHANGELOG.md
  examples/yew-tailwindcss/Trunk.toml
  examples/yew-tailwindcss/index.html
  examples/yew-tailwindcss/src/app.css
  examples/yew-tailwindcss/src/index.scss
  examples/yew-tailwindcss/src/inline-scss.scss
  examples/yew-tailwindcss/tailwind.config.js
  site/content/assets.md
  src/pipelines/mod.rs
  src/pipelines/tailwind_css.rs
  src/tools.rs
Labels: disposition:merge

#514 Update list of example projects built in CI
  .github/workflows/ci.yaml
  CHANGELOG.md
  examples/webworker-gloo/Trunk.toml
  examples/webworker/Trunk.toml
Labels: ci/cd

#488 Allow projects without rust
  .github/workflows/ci.yaml
  CHANGELOG.md
  examples/no-rust/Trunk.toml
  examples/no-rust/index.html
  examples/no-rust/index.scss
  src/pipelines/html.rs
Labels: discussion

#501 feat: show actual addresses if `0.0.0.0` is used
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/common.rs
  src/serve.rs
Labels: disposition:merge
